### ISSUE TITLE
add to pypi

### ISSUE THREAD

**Issue by faroit** [DavidDiazGuerra/gpuRIR#1]
this is a great (and useful) effort. 👏 

I would like to add this project to the [awesome scientific audio](https://github.com/faroit/awesome-python-scientific-audio) list. Do you plan to push a release to pypi?

**Comment by DavidDiazGuerra** [comment]
I have not thought too much about that, I think I should test it on more platforms before publishing it on PyPI. Maybe I will do it in the future, after receiving some feedback.

Of course, I'm glad you add the project to [impressive scientific audio](https://github.com/faroit/awesome-python-scientific-audio).
