### ISSUE TITLE
Source Directivity

### ISSUE THREAD

**Issue by schmiph2** [DavidDiazGuerra/gpuRIR#16]
Hi David

Thank you for this great library! Do you have plans to include the directivity of the sources in the library? Would it even be possible to add them to your library?

**Comment by DavidDiazGuerra** [comment]
Hi schmiph2,

Including non omnidirectional sources in the library is a great idea, but I'm afraid I don't have time time to implement it in the near future. Nevertheless, if anyone wants to try to do it, it should be possible and, actually, not too difficult. 

The directivity of the receiver is included in: 
https://github.com/DavidDiazGuerra/gpuRIR/blob/c1279cd94edf122a565c0973e694ef279829ebbc/src/gpuRIR_cuda.cu#L342
through the function `mic_directivity`:
https://github.com/DavidDiazGuerra/gpuRIR/blob/c1279cd94edf122a565c0973e694ef279829ebbc/src/gpuRIR_cuda.cu#L132
This function first computes the angle between the steering vector of the microphone and the vector with the direction of arrival (DOA) of the image source and then apply the desired directivity pattern.

The directivity of the sources could be implemented in a similar way, but computing the angle bwtween the steering vector of the source (which should be added as a new parameter of the `simulateRIR` function) and the normal vector of the first reflection wall.

I'll try to implement it in the future if nobody does it before, but I don't know when I'll have time to do it.

**Comment by schmiph2** [comment]
Hi David

Thank you for your answer an the hints for the implementing the source directivity and sorry for my late reply.  I will check if I can find a student for the implementation.  I will let you know if we start the implementation.

**Comment by catherine-qian** [comment]
Hi all
Thanks for the discussion on this issue. just wondered whether there is an existing RIR generator that can simulate speaking head orientation?

**Comment by DavidDiazGuerra** [comment]
Hi Catherine,

[Pyroomacoustics](https://github.com/LCAV/pyroomacoustics) is one of the most comprehensive acoustic simulation libraries for Python, but I don't know if it includes that feature.

**Comment by catherine-qian** [comment]
thanks for your reply！
