### ISSUE TITLE
'GPUassert: unknown error' (gpuRIR_cuda.cu line 1002) when importing the module

### ISSUE THREAD

**Issue by GaetanLepage** [DavidDiazGuerra/gpuRIR#17]
Hello,

I have a strange problem while importing the gpuRIR library: (simply calling `python -c "import gpuRIR"`).
Indeed, I get the following error:
`GPUassert: unknown error /home/gaetan/inria/repo/rir_simulation/gpuRIR/src/gpuRIR_cuda.cu 1002`

This only happens on one of my machine:
GPUs:  GTX 1070 and GTX 1080
OS: Arch Linux
Python version: same behavious with both 3.7 and 3.9
Cuda version: 11.2
Nvidia driver: 460.56

The error does not occur on my other machine:
GPU:  Quadro RTX4000
OS: Ubuntu 18.04
Python version: works with both 3.7 and 3.8
Cuda version: 11.2
Nvidia driver: 460.56

Do you have an idea where this problem could be coming from ?

**Comment by DavidDiazGuerra** [comment]
Hello Gaétan,

I've never tested the library having multiple GPUs, I guess the error may be related to that. I'll try to get access to a machine with multiple GPUs next week and make some tests, but I'm not sure if I'll be able.

Thank you very much for reporting the bug.

**Comment by GaetanLepage** [comment]
Hello David,

Weirdly, trying it again today (after a reboot) made it work !
Not sure what was the problem there ^^ but hey, it works now: thanks !

**Comment by DavidDiazGuerra** [comment]
Cool, let me know if the problem arises again.
