### ISSUE TITLE
Bug in "beta_SabineEstimation" when given optional parameter abs_weights

### ISSUE THREAD

**Issue by Nelsonvon** [DavidDiazGuerra/gpuRIR#22]
Hi,

It seems that the function will return incorrect beta value when abs_weights is given and the maximum is not 1.0.

As in the sub-function t60error, abs_weights is normalized, the return of beta_SabineEstimation should be consistent with that and be np.sqrt(1 - result.x * abs_weights/ **np.array(abs_weights).max()** ).astype(np.float32) instead (See line 54. gpuRIR.__init__.py).

Otherwise the beta value computed will be higher that the actual one.

Kind regards,

Nelson

**Comment by DavidDiazGuerra** [comment]
Hi Nelson,

You are right, `abs_weights` should be normalized at the beginning of the `beta_SabineEstimation ` function, not inside the subfunction. I'll fix it now.

Thank you!

**Comment by DavidDiazGuerra** [comment]
I think the bug should be fixed now with the last commit. Thank you again for reporting it.

Best regards,
David
