### ISSUE TITLE
Generated signal contains noise

### ISSUE THREAD

**Issue by zly19** [DavidDiazGuerra/gpuRIR#35]
Hello, I tried to simulate a moving sound source with simulate_trajectory.py, but why does the generated multi-channel signal contain a lot of noise?

room_sz = [6,6,3]  # Size of the room [m]
traj_pts = 64  # Number of trajectory points
pos_traj = np.tile(np.array([0.0,2.0,1.0]), (traj_pts,1))
pos_traj[:,0] = np.linspace(0.5, 5.5, traj_pts) # Positions of the trajectory points [m]
nb_rcv = 6 # Number of receivers
pos_rcv  = np.c_[
                [3.+0.035,   3.,                     1.],
                [3.+0.035/2, 3.0+np.sqrt(3)*0.035/2, 1.],
                [3.-0.035/2, 3.0+np.sqrt(3)*0.035/2, 1.],
                [3.-0.035,   3.,                     1.],
                [3.-0.035/2, 3.0-np.sqrt(3)*0.035/2, 1.],
                [3.+0.035/2, 3.0-np.sqrt(3)*0.035/2, 1.]]	 # Position of the receivers [m]
pos_rcv = pos_rcv.T
print("pos_rcv",pos_rcv.shape)
mic_pattern = "omni" # Receiver polar pattern
T60 = 0.3 # Time for the RIR to reach 60dB of attenuation [s]
att_diff = 15	# Attenuation when start using the diffuse reverberation model [dB]
att_max = 60.0 # Attenuation at the end of the simulation [dB]
beta = gpuRIR.beta_SabineEstimation(room_sz, T60) # Reflection coefficients
Tdiff= gpuRIR.att2t_SabineEstimator(att_diff, T60) # Time to start the diffuse reverberation model [s]
Tmax = gpuRIR.att2t_SabineEstimator(att_max, T60)	 # Time to stop the simulation [s]
nb_img = gpuRIR.t2n( Tdiff, room_sz )	# Number of image sources in each dimension
RIRs = gpuRIR.simulateRIR(room_sz, beta, pos_traj, pos_rcv, nb_img, Tmax, fs, Tdiff=Tdiff, mic_pattern=mic_pattern)
filtered_signal = gpuRIR.simulateTrajectory(source_signal, RIRs)
wavfile.write('filtered_signal.wav', fs, filtered_signal)

**Comment by DavidDiazGuerra** [comment]
Hi Zly,

I've been checking your simulation setup and the RIRs generated with it don't look bad. I can't tell about the generated multi-channel signal since that will depend on your `source_signal`. What kind of noise does it have? Could it already be present in your `source_signal`?

**Comment by zly19** [comment]
Hi David.

The source signal is a clean voice signal, and its waveform and spectrogram are as follows:
![Snipaste_2022-06-27_15-18-08](https://user-images.githubusercontent.com/77422958/175883471-5d2000c8-9095-4c60-a908-936f99ca95d5.jpg)


The speech spectrogram of the first channel in the output multi-channel speech signal is shown in the figure:

![Snipaste_2022-06-27_15-25-40](https://user-images.githubusercontent.com/77422958/175883519-163b8110-5091-420c-83ae-727219164a29.jpg)

 Thanks for your help!

**Comment by DavidDiazGuerra** [comment]
Rather than having noise, the output signal looks like having been clipped. When the input is an array, `wavfile.write` expects the maximum and minimum values of the signal to be 1 and -1, maybe `filtered_signal` is exceeding these limits?

**Comment by zly19** [comment]
Thank you very much! The problem is solved, it is indeed because the output signal amplitude exceeds the limit.
