### ISSUE TITLE
an error occured when using gpuRIR.simulateTrajectory

### ISSUE THREAD

**Issue by jason-wuwu** [DavidDiazGuerra/gpuRIR#41]
Hi! Thank you for your awesome library. Currently, I am using gpuRIR in my code. However, when I generate my data, there always exists an error "**_cuFFT error: 5 /tmp/pip-req-build-y4n86nx1/src/gpuRIR_cuda.cu 978_**". 
I am quite new to this library, could you please help me with this? Thank you so much!

**Comment by DavidDiazGuerra** [comment]
Hi Jason,

It's hard to tell with that information, but I would say you're probably
running out of GPU memory. Would that be possible?

**Comment by jason-wuwu** [comment]
Hi！I have solved the problem. I did run out of the GPU memory. Thank you so much for point out this.
