### ISSUE TITLE
An error occurs when calling after the installation is complete.

### ISSUE THREAD

**Issue by NiniAndy** [DavidDiazGuerra/gpuRIR#42]
(torch_env) zhuang@amax:~$ pip install cmake
Collecting cmake
  Downloading cmake-3.26.1-py2.py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (24.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.0/24.0 MB 1.1 MB/s eta 0:00:00
Installing collected packages: cmake
Successfully installed cmake-3.26.1
(torch_env) zhuang@amax:~$ pip install  https://github.com/DavidDiazGuerra/gpuRIR/zipball/master
Collecting https://github.com/DavidDiazGuerra/gpuRIR/zipball/master
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='github.com', port=443): Read timed out. (read timeout=15)")': /DavidDiazGuerra/gpuRIR/zipball/master
  Downloading https://github.com/DavidDiazGuerra/gpuRIR/zipball/master
     \ 698.5 kB 1.5 MB/s 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: gpuRIR
  Building wheel for gpuRIR (setup.py) ... done
  Created wheel for gpuRIR: filename=gpuRIR-1.2.0-cp37-cp37m-linux_x86_64.whl size=458068 sha256=bc04d5dfaa6f34b9380e12012ba5c1e4aca6aa4582dffa2810419a1befad24f0
  Stored in directory: /tmp/pip-ephem-wheel-cache-bi0498gj/wheels/4a/21/c3/ecebf86781b6956140ea1030a6209ca0c286bd6c633619cb01
Successfully built gpuRIR
Installing collected packages: gpuRIR
Successfully installed gpuRIR-1.2.0
(torch_env) zhuang@amax:~$ python
Python 3.7.15 (default, Nov 24 2022, 21:12:53)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import gpuRIR
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhuang/anaconda3/envs/torch_env/lib/python3.7/site-packages/gpuRIR/__init__.py", line 9, in <module>
    from gpuRIR_bind import gpuRIR_bind
ImportError: /home/zhuang/anaconda3/envs/torch_env/lib/python3.7/site-packages/gpuRIR_bind.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cufftExecC2R

This error occurred when I called after the installation was complete.

My nvcc is 11.1.74：
(torch_env) zhuang@amax:~$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Tue_Sep_15_19:10:02_PDT_2020
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.TC455_06.29069683_0

my gcc is 9.3.0：
(torch_env) zhuang@amax:~$ gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

my ubuntu is  Ubuntu 20.04.1 LTS

**Comment by DavidDiazGuerra** [comment]
Hi! I wasn't able to reproduce the issue, but I would say this is a problem with the CUDA installation rather than with gpuRIR. Could you do `echo $LD_LIBRARY_PATH` and see if `/usr/local/cuda/lib64` (or something similar) is in your LD PATH?

**Comment by TioSisai** [comment]
@DavidDiazGuerra Thanks for your kindness! This problem has already been solved. It seems that there are some errors in the cuda_toolkit. I removed the original one, and reinstall a new version, then no errors.

**Comment by ycyang133** [comment]
Dear @DavidDiazGuerra,
I also meet this question recently.
To solve this, I add `os.environ['LD_LIBRARY_PATH'] = "/usr/local/cuda/lib64"
` in my code. However, this error still occurs. 
Could you please share some more suggestions besides reinstalling the Cuda for me?
Thank you very much.

**Comment by DavidDiazGuerra** [comment]
Hi @ycyang133,

Where are you adding that line?

Could you try to do `echo $LD_LIBRARY_PATH` just before trying to install the library and see what it returns?
