### ISSUE TITLE
Compute30 is deprecated for nvcc 530 

### ISSUE THREAD

**Issue by JuanFMontesinos** [DavidDiazGuerra/gpuRIR#47]
Hi :) 
hope you are doing well.
Just mentioning the library was failing when compiled for drivers version 530.
https://github.com/DavidDiazGuerra/gpuRIR/blob/283235d57ac01c51d0f43913deb73dfb2470be8c/CMakeLists.txt#L10
```
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [82 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/gpuRIR
      copying gpuRIR/__init__.py -> build/lib.linux-x86_64-cpython-310/gpuRIR
      running build_ext
      -- The CXX compiler identification is GNU 9.4.0
      -- The CUDA compiler identification is NVIDIA 12.2.91
      -- Check for working CXX compiler: /usr/bin/c++
      -- Check for working CXX compiler: /usr/bin/c++ -- works
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Check for working CUDA compiler: /usr/local/cuda-12.2/bin/nvcc
      -- Check for working CUDA compiler: /usr/local/cuda-12.2/bin/nvcc -- works
      -- Detecting CUDA compiler ABI info
      -- Detecting CUDA compiler ABI info - done
      -- Looking for C++ include pthread.h
      -- Looking for C++ include pthread.h - found
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Looking for pthread_create in pthreads
      -- Looking for pthread_create in pthreads - not found
      -- Looking for pthread_create in pthread
      -- Looking for pthread_create in pthread - found
      -- Found Threads: TRUE
      -- Found CUDA: /usr/local/cuda-12.2 (found version "12.2")
      -- Found PythonInterp: /home/jmt/.mlflow/envs/mlflow-dea84f7f3ec804ae1d7f6843ff7170c9178c7aab/bin/python (found version "3.10.6")
      -- Found PythonLibs: /home/jmt/.pyenv/versions/3.10.6/lib/libpython3.10.so
      -- pybind11 v2.2.0
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /tmp/pip-req-build-vck4k6y4/build/temp.linux-x86_64-cpython-310
      Scanning dependencies of target gpuRIRcu
      [ 25%] Building CUDA object CMakeFiles/gpuRIRcu.dir/src/gpuRIR_cuda.cu.o
      nvcc fatal   : Unsupported gpu architecture 'compute_30'
```
I imagine nvidia deprecated support for that generation. Just letting you know in case you can manager what is considered as "Common". 
It can be easily patched by switching from Common to Auto.

**Comment by DavidDiazGuerra** [comment]
Hi! This is a recurrent problem that happens each time Nvidia deprecates an architecture till CMake removes it from the "common" architectures. I don't really know how to fix it, the `Auto` option is not a good solution since it only compiles the library for the architecture of the current GPU in the machine doing the compilation, but in many clusters, you compile the library in a login node with a different architecture than the present in the compute nodes that will run it.

**Comment by JuanFMontesinos** [comment]
Yep, I imagine. I think you can pass a custom list so that you have control on it. 
Anyway I was just reporting it you to be aware of it.  :)

Best
Juan

**Comment by DavidDiazGuerra** [comment]
Yes, that's basically what I do when someone reports this kind of issues
and doesn't know how to fix it themselves. I ask what GPUs are using and
create a branch for them with those architectures. I don't know how other
libraries deal with this tbh, but it's a quite annoying problem.
