### ISSUE TITLE
position

### ISSUE THREAD

**Issue by yunzqq** [DavidDiazGuerra/gpuRIR#48]
Is the center the coordinate of origin?

**Comment by DavidDiazGuerra** [comment]
Hi Qiquan,

The point (0,0,0) is the south-west corner of the room at ground height, so the coordinates of the source and receiver positions should be in the range from (0,0,0) to the size of the room.

Best,
David

**Comment by yunzqq** [comment]
> Hi Qiquan,
> 
> The point (0,0,0) is the south-west corner of the room at ground height, so the coordinates of the source and receiver positions should be in the range from (0,0,0) to the size of the room.
> 
> Best, David

Thank you for your reply!
