### ISSUE TITLE
question for orV_rcv configuration

### ISSUE THREAD

**Issue by yhgon** [DavidDiazGuerra/gpuRIR#5]
I have question to configure card recv. 

for calculate amp, it use related [vector of source and recv position](https://github.com/DavidDiazGuerra/gpuRIR/blob/master/src/gpuRIR_cuda.cu#L241)  `vec[d] = clust_pos[d] + (1-2*rflx_idx[d]) * sh_pos_src[m_src*3+d] - sh_pos_rcv[m_rcv*3+d];`

so I'm confusing when I set up cardiac microphone as below,   
```
room_sz = [8,8,8]
nb_src = 1  # Number of sources
pos_src = np.array([ [1,1,0.5] ]) # Positions of the source  [x,y,z position] 
nb_rcv = 5 # Number of receivers
pos_rcv = np.array([ [4,4,1.5], [4,4,1.5], [4,4,1.5], [4,4,1.5], [4,4,1.5]   ] )	 # same position  [m] [x,y,z] position
```
how to configure the orV base on clockwise(north direction)  ? 
for example, 0 degree, 45 degree, 90 degree(north direction), 135 degree and 180 degree. 
```
orV_rcv = np.array([  [?,?,0],  [?,?,0],  [?,?,0],  [?,?,0],  [?,?,0]  ]   )
mic_pattern = "card" # Receiver polar pattern
```

**Comment by DavidDiazGuerra** [comment]
In the [line you pointed out](https://github.com/DavidDiazGuerra/gpuRIR/blob/master/src/gpuRIR_cuda.cu#L241) `vec` is calculated as the vector going from the receiver to the image source, so its module is the distance between them. To calculate the amplitude, first, [the distance is used to model the spherical propagation of the sound](https://github.com/DavidDiazGuerra/gpuRIR/blob/master/src/gpuRIR_cuda.cu#L245), and then [the directivity of the receiver is added](https://github.com/DavidDiazGuerra/gpuRIR/blob/master/src/gpuRIR_cuda.cu#L246). To model the directivity of the receiver, the cosine of the angle between `vec` and `orV` is [computed](https://github.com/DavidDiazGuerra/gpuRIR/blob/master/src/gpuRIR_cuda.cu#L116).

For example, you can simulate a cardioid microphone that points to a source in the north direction in anechoic chamber with:

```
room_sz = [10,10,10]  # Size of the room [m]
nb_src = 1  # Number of sources
pos_src = np.array([[5,7,5]]) # Positions of the sources [m]
nb_rcv = 1 # Number of receivers
pos_rcv = np.array([[5,5,5]])	 # Position of the receivers [m]
orV_rcv = np.array([[0,1,0]])
mic_pattern = "card" # Receiver polar pattern
fs=16000.0 # Sampling frequency [Hz]

beta = np.zeros(6) # Reflection coefficients
Tmax = 0.05	 # Time to stop the simulation [s]
Tdiff= Tmax  # Time to start the diffuse reverberation model [s]
nb_img = gpuRIR.t2n( Tdiff, room_sz )	# Number of image sources in each dimension
RIRs = gpuRIR.simulateRIR(room_sz, beta, pos_src, pos_rcv, nb_img, Tmax, fs, Tdiff=Tdiff, orV_rcv=orV_rcv, mic_pattern=mic_pattern)
```

If you, for instance, point the microphone to the east `orV_rcv = np.array([[1,0,0]])` you will see how the amplitude of the RIR is cut in half, or if you point the mic to south direction `orV_rcv = np.array([[0,-1,0]])` you won't receive anything.

I think that, for the array you want (0 degree, 45 degree, 90 degree(north direction), 135 degree and 180 degree), you need to use:

`orV_rcv = np.array([  [1,0,0],  [1,1,0],  [0,1,0],  [-1,1,0],  [-1,0,0]  ]   )`

As you can see, orV doesn't need to be unitary, only its direction matter.

I hope it helps.

**Comment by yhgon** [comment]
Thanks for the confirmation of vector coordinate  and detail information.
