### ISSUE TITLE
Can gpurir run with multiprocessing?

### ISSUE THREAD

**Issue by fromprimary** [DavidDiazGuerra/gpuRIR#58]
I try to generate rir when training, but when I user torch.utils.data.DataLoaderto generate data, there is error :GPUassert: initialization error /data/tangyf/preprocess/gpuRIR-master/src/gpuRIR_cuda.cu 793. Even I set the tnum_workers to 1, the error still happen. But when I set num_workers to 0, no error happened.

**Comment by DavidDiazGuerra** [comment]
Please, check #37
