### ISSUE TITLE
How does gpuRIR handle the discrimination of absorption coefficients for each frequency band?

### ISSUE THREAD

**Issue by albuca09** [DavidDiazGuerra/gpuRIR#70]
Hello! Thank you for this repository! I have one question. In example.py (below), the line: abs_weights = [0.9]*5+[0.5] # 

absorption coeff = │ [0.47 (L_1, F_125), 0.91 (L_2, F_125), 0.47 (L_3, F_125), 0.9 (L_4, F_125), 0.78 (L_5, F_125), 0.53 (L_6, F_125), 0.06 (L_1, F_250), 0.06 (L_2, F_250), 0.06 (L_3, F_250), 0.06 (L_4, F_250), 0.06 (L_5, F_250), 0.06 (L_6, F_250), 0.06 (L_1, F_500), 0.06 (L_2, F_500), 0.06 (L_3, F_500), 0.06 (L_4, F_500), 0.06 (L_5, F_500), 0.06 (L_6, F_500), 0.06 (L_1, F_1000), 0.06 (L_2, F_1000), 0.06 (L_3, F_1000), 0.06 (L_4, F_1000), 0.06 (L_5, F_1000), 0.06 (L_6, F_1000), 0.06 (L_1, F_2000), 0.06 (L_2, F_2000), 0.06 (L_3, F_2000), 0.06 (L_4, F_2000), 0.06 (L_5, F_2000), 0.06 (L_6, F_2000), 0.06 (L_1, F_4000), 0.02 (L_2, F_4000), 0.02 (L_3, F_4000), 0.02 (L_4, F_4000), 0.02 (L_5, F_4000), 0.02 (L_6, F_4000)]  
Where 𝐿_𝑖, represents surfaces and 𝐹_𝑗  represents frequencies.

How does gpuRIR handle the discrimination of absorption coefficients for each frequency band?

Thank you!!!

========

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
""" Example for computing the RIR between several sources and receivers in GPU.
"""

import numpy as np
import numpy.matlib
import matplotlib.pyplot as plt
from math import ceil

import gpuRIR
gpuRIR.activateMixedPrecision(False)
gpuRIR.activateLUT(True)

room_sz = [3,3,2.5]  # Size of the room [m]
nb_src = 2  # Number of sources
pos_src = np.array([[1,2.9,0.5],[1,2,0.5]]) # Positions of the sources ([m]
nb_rcv = 3 # Number of receivers
pos_rcv = np.array([[0.5,1,0.5],[1,1,0.5],[1.5,1,0.5]])	 # Position of the receivers [m]
orV_rcv = np.matlib.repmat(np.array([0,1,0]), nb_rcv, 1) # Vectors pointing in the same direction than the receivers
mic_pattern = "card" # Receiver polar pattern
abs_weights = [0.9]*5+[0.5] # Absortion coefficient ratios of the walls
T60 = 1.0	 # Time for the RIR to reach 60dB of attenuation [s]
att_diff = 15.0	# Attenuation when start using the diffuse reverberation model [dB]
att_max = 60.0 # Attenuation at the end of the simulation [dB]
fs=16000.0 # Sampling frequency [Hz]

beta = gpuRIR.beta_SabineEstimation(room_sz, T60, abs_weights=abs_weights) # Reflection coefficients
Tdiff= gpuRIR.att2t_SabineEstimator(att_diff, T60) # Time to start the diffuse reverberation model [s]
Tmax = gpuRIR.att2t_SabineEstimator(att_max, T60)	 # Time to stop the simulation [s]
nb_img = gpuRIR.t2n( Tdiff, room_sz )	# Number of image sources in each dimension
RIRs = gpuRIR.simulateRIR(room_sz, beta, pos_src, pos_rcv, nb_img, Tmax, fs, Tdiff=Tdiff, orV_rcv=orV_rcv, mic_pattern=mic_pattern)

t = np.arange(int(ceil(Tmax * fs))) / fs
plt.plot(t, RIRs.reshape(nb_src*nb_rcv, -1).transpose())
plt.show()

**Comment by DavidDiazGuerra** [comment]
Hello. Unfortunately, gpuRIR doesn't support frequency-dependant attenuation.

**Comment by albuca09** [comment]
Do you consider it very labor-intensive to implement this support in gpuRIR?

**Comment by albuca09** [comment]
thank you!. In this case, what is the best way to choose absorption
coefficients?



Em sex., 13 de dez. de 2024 às 08:45, David Díaz-Guerra Aparicio <
***@***.***> escreveu:

**Comment by DavidDiazGuerra** [comment]
The best way to choose the absorption coefficients depends on your application. The simulation function works with reflection coefficients, which can be computed with `gpuRIR.beta_SabineEstimation`. You can include relative absorption of every wall if you want every wall to have different reflection coefficients, but for many applications just using the default value (all walls are equal) might be enough.

About implementing frequency-dependant absorption, I don't have time to do it and it would probably have a quite important impact on the RIR estimation time, which is the main advantage of `gpuRIR`. I created `gpuRIR` to be able to simulate huge amounts of RIRs to be used for training deep-learning models, if you need highly realistic RIRs to be listened to, I would recomend you using other RIR simulation libraries that are slower but allow you to simulate frequency-dependant absorption walls, air absorption, and other physical phenomena.

**Comment by albuca09** [comment]
thank you!

**Comment by albuca09** [comment]
Good evening,  
I managed to overcome the limitation of absorption coefficients by frequency. Here's what I did: I ran a separate simulation for each frequency band, considering the respective absorption coefficients, then filtered the results by band and summed them up.  

I would like to know if I can implement this method in your simulator and perform calibrations using real impulse responses.

**Comment by DavidDiazGuerra** [comment]
Hello,

That implementation should work, but it's quite inefficient since it multiplies the simulation time by the number of frequency bands. That's the reason I didn't include it in gpuRIR, which is focused on performing fast simulations.

I'm not sure what you mean by performing calibrations using real impulse responses.
